package br.com.bancodigital.exception;

public enum CodigoErro {
    SALDO_INSUFICIENTE,
    CLIENTE_REGISTRADO,
    CLIENTE_CPF_INVALIDO,
    FUNCIONARIO_REGISTRADO,
    FUNCIONARIO_COD_INVALIDO,
    FUNCIONARIO_CPF_INVALIDO,
    LIMITE_INSUFICIENTE_CC,
    ERRO_GERACAO_CARTAO;
    ;
}
